[package]
name = "webapp"
version = "0.1.0"
edition.workspace = true

[dependencies]
askama = "0.12.1"
axum.workspace = true
serde.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http = { version = "0.6.2", features = ["fs"] }
